module.exports = {
  USER_COUNT: 10,
  VIDEO_COUNT: 30,
  COMMENT_COUNT: 100,
  TWEET_COUNT: 30,

  VIDEO_LIKE_COUNT: 120,
  COMMENT_LIKE_COUNT: 150,
  TWEET_LIKE_COUNT: 60,

  PLAYLIST_COUNT: 10,
  PLAYLIST_VIDEO_COUNT: 40,

  SUBSCRIPTION_COUNT: 30,
  WATCH_HISTORY_COUNT: 80,
};